### ISSUE TITLE
Build error: too many arguments in call to yaml.NewDecoder

### ISSUE THREAD

**Issue by eclipseo** [docker/compose-on-kubernetes#115]
With Golang 1.12.6:
```
BUILDSTDERR: # github.com/docker/compose-on-kubernetes/internal/parsing
BUILDSTDERR: _build/src/github.com/docker/compose-on-kubernetes/internal/parsing/loader.go:14:22: too many arguments in call to yaml.NewDecoder
BUILDSTDERR: _build/src/github.com/docker/compose-on-kubernetes/internal/parsing/loader.go:14:45: undefined: yaml.WithLimitDecodedValuesCount
```

NewDecoder seems to only take one argument:

https://github.com/docker/compose-on-kubernetes/blob/7d98bfa0e73dbcf774624f1fb0ab2d3644309f94/vendor/gopkg.in/yaml.v2/decode.go#L245-L249

I can't find yaml.WithLimitDecodedValuesCount anywhere.

**Comment by eclipseo** [comment]
Seems to depend on https://github.com/go-yaml/yaml/pull/375

**Comment by silvin-lubecki** [comment]
You are right about the PR on `go-yaml`, but since it was never merged, the project depends on a fork of this library : https://github.com/docker/compose-on-kubernetes/blob/master/Gopkg.toml#L67
It adds a fix to avoid the infamous YAML bomb https://github.com/docker/compose-on-kubernetes/blob/master/internal/parsing/loader_test.go#L17

How are you building the project? I wonder how you got this error as the dependency is vendored and versioned... I'll close this issue but feel free to re-open it if you think this answer doesn't help you fix the issue 👍

**Comment by eclipseo** [comment]
I am building the project unbundled, not using go modules yet (don't have the tooling distro side yet). So I need to build each dependency separately. I've used simonferquel fork and replaced the import path accordingly. I have yet to test it but it should work.

**Comment by silvin-lubecki** [comment]
The project does not use `go modules` yet but [dep](https://golang.github.io/dep/) instead. As the vendoring is embedded and versioned I still don't understand why do you need those manual steps?
Are you wiping the `vendor` directory?
