### ISSUE TITLE
How do I install compose-on-kubernetes on Play with Kubernetes?

### ISSUE THREAD

**Issue by GitHub30** [docker/compose-on-kubernetes#35]
Can I run compose-on-kubernete on PWK?

https://labs.play-with-k8s.com/

**Comment by herveleclerc** [comment]
Hi,

pwk is not working well at this time :( but here is the procedure

https://labs.play-with-k8s.com
create a 1 master and n worker nodes like said in welcome motd


`kubectl create namespace compose`

```
curl https://storage.googleapis.com/kubernetes-helm/helm-v2.12.1-linux-amd64.tar.gz -o helm-v2.12.1-linux-amd64.tar.gz``

tar xvf helm-v2.12.1-linux-amd64.tar.gz

export PATH=$PATH:/root/linux-amd64

kubectl -n kube-system create serviceaccount tiller

kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

helm init --service-account tiller --upgrade
# wait until helm list works
helm list
helm install --name etcd-operator stable/etcd-operator --namespace compose
```

```
kubectl apply -f - << EOF
 apiVersion: "etcd.database.coreos.com/v1beta2"
 kind: "EtcdCluster"
 metadata:
   name: "compose-etcd"
   namespace: "compose"
 spec:
   size: 3
   version: "3.2.13"
EOF
```

You will have to clone the repo https://github.com/docker/compose-on-kubernetes and change Makefile to compile binaries with CGO_ENABLED=0

on my mac

`Makefile`

```
bin/%: cmd/% FORCE
	@echo "🌟 $@"
	@GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build $(VERBOSE_GO) $(GOBUILD_FLAGS) -ldflags=$(LDFLAGS) -o $@$(EXEC_EXT) ./$<
```

I also changed common.mk file

```
IMAGE_REPO_PREFIX ?= $(REGISTRY_ORG)/kube-compose-

to

IMAGE_REPO_PREFIX ?= $(REGISTRY_ORG)/kube-compose-dev

```


If you want to grab it you can get here (link available 7 days ) : 
"https://minio.caas.fr/hleclerc/startup-1.pptx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio4alterway%2F20190108%2F%2Fs3%2Faws4_request&X-Amz-Date=20190108T073122Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=18209d5c1d6669bb827f8aacdd34024b155a4e6a44519bbe501bca762337614e"

Get the installer binary on play with k8s

`chmod a+x installer`

`./installer -namespace=compose -etcd-servers=http://compose-etcd-client:2379 -tag=v0.4.16 -skip-liveness-probes=true`


Check with :

`kubectl api-versions | grep compose`

You should have :
```
compose.docker.com/v1beta1
compose.docker.com/v1beta2
```

Get the example https://github.com/docker/compose-on-kubernetes/blob/master/samples/docker-compose.yml
Remove any reference to volume because pwk by default has no storage configured
then deploy it

`docker stack deploy -c docker-compose.yml --orchestrator=kubernetes mystack`

Check stack is deployed

`kubectl get stacks`

**Comment by simonferquel** [comment]
@herveleclerc Could you make a PR out of this for documenting installation on PWK?

**Comment by collabnix** [comment]
Tested it and it worked like a charm. All I tried putting it under script https://github.com/collabnix/compose-on-kubernetes/blob/master/scripts/pwk/prepare-pwk.sh to keep it simple. The only issue I faced was sometimes the tiller deploy pod took more time to come up.

**Comment by GitHub30** [comment]
@collabnix 
Thank you. It works very well on PWK:)
```bash
git clone https://github.com/collabnix/compose-on-kubernetes.git \
    && cd compose-on-kubernetes/scripts/pwk/ \
    && bash bootstrap-pwk.sh \
    && bash prepare-pwk.sh
```

**Comment by collabnix** [comment]
Thanks for giving a try @GitHub30. All eyes on CNAB & see how it can simplify things.

**Comment by ijc** [comment]
@collabnix are you planning on opening a PR with your changes/additions?

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
